///////////////////////////////////////////////////////////
//  Hobo.cs
//  Implementation of the Class Hobo
//  Generated by Enterprise Architect
//  Created on:      11-May-2018 8:24:45 PM
//  Original author: STUDENT
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Hobo : Person {

	public Hobo(){

	}

	~Hobo(){

	}

	/// <summary>
	/// calls the base constructor with the same signature
	/// </summary>
	/// <param name="pFName"></param>
	/// <param name="pLName"></param>
	/// <param name="pGender"></param>
	public Hobo(string pFName, string pLName, string pGender){

	}

	/// <summary>
	/// Calls the base constructor with the same signature
	/// </summary>
	/// <param name="pGender"></param>
	public Hobo(string pGender){

	}

	/// <summary>
	/// Overrides the person abstract method
	/// 
	/// Needs to return "Find A Place To Sleep"
	/// </summary>
	public string Work(){

		return "";
	}

}//end Hobo