///////////////////////////////////////////////////////////
//  ITeach.cs
//  Implementation of the Interface ITeach
//  Generated by Enterprise Architect
//  Created on:      11-May-2018 8:24:45 PM
//  Original author: STUDENT
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ITeach  {

	string Teach();
}//end ITeach