///////////////////////////////////////////////////////////
//  PAVETeacher.cs
//  Implementation of the Class PAVETeacher
//  Generated by Enterprise Architect
//  Created on:      11-May-2018 8:24:45 PM
//  Original author: STUDENT
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class PAVETeacher : Teacher {

	public PAVETeacher(){

	}

	~PAVETeacher(){

	}

	/// <summary>
	/// Calls the base constructor with the same signature
	/// 
	/// THEN creates a new TeachPAVE and assignes it to the TeachBehaviour attribute
	/// </summary>
	/// <param name="pStaffID"></param>
	/// <param name="pFName"></param>
	/// <param name="pLName"></param>
	/// <param name="pGender"></param>
	public PAVETeacher(int pStaffID, string pFName, string pLName, string pGender){

	}

	/// <summary>
	/// This overrides the parent implementation
	/// 
	/// This should return "PAVE Teacher"
	/// </summary>
	public virtual string GetOccupation(){

		return "";
	}

}//end PAVETeacher