///////////////////////////////////////////////////////////
//  SecondaryTeacher.cs
//  Implementation of the Class SecondaryTeacher
//  Generated by Enterprise Architect
//  Created on:      11-May-2018 8:24:45 PM
//  Original author: STUDENT
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SecondaryTeacher : Teacher {

	public SecondaryTeacher(){

	}

	~SecondaryTeacher(){

	}

	/// <summary>
	/// Calls the base constructor with the same signature
	/// 
	/// THEN creates a new TeachHighSchool and assigns it to the TeachBehaviour
	/// attribute
	/// </summary>
	/// <param name="pStaffID"></param>
	/// <param name="pFName"></param>
	/// <param name="pLName"></param>
	/// <param name="pGender"></param>
	public SecondaryTeacher(int pStaffID, string pFName, string pLName, string pGender){

	}

	/// <summary>
	/// This overrides the parent implementation
	/// 
	/// This should return "PAVE Teacher"
	/// </summary>
	public override string GetOccupation(){

		return "";
	}

}//end SecondaryTeacher