///////////////////////////////////////////////////////////
//  SpecialNeedsTeacher.cs
//  Implementation of the Class SpecialNeedsTeacher
//  Generated by Enterprise Architect
//  Created on:      11-May-2018 8:24:45 PM
//  Original author: STUDENT
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SpecialNeedsTeacher : Teacher {

	public SpecialNeedsTeacher(){

	}

	~SpecialNeedsTeacher(){

	}

	/// <summary>
	/// Calls the base constructor with the same signature
	/// 
	/// THEN creates a new TeachSpecialNeeds and assigns it to the TeachBehaviour
	/// attribute
	/// </summary>
	/// <param name="pStaffID"></param>
	/// <param name="pFName"></param>
	/// <param name="pLName"></param>
	/// <param name="pGender"></param>
	public SpecialNeedsTeacher(int pStaffID, string pFName, string pLName, string pGender){

	}

}//end SpecialNeedsTeacher