///////////////////////////////////////////////////////////
//  Student.cs
//  Implementation of the Class Student
//  Generated by Enterprise Architect
//  Created on:      11-May-2018 8:24:45 PM
//  Original author: STUDENT
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Student : Person {

	private string StudentID;

	public Student(){

	}

	~Student(){

	}

	/// <summary>
	/// Calls Base Constructor with (pFname, pLName, pGender) signature
	/// 
	/// Populates StudentID with PStudentID
	/// </summary>
	/// <param name="pStudentId"></param>
	/// <param name="pFName"></param>
	/// <param name="pLName"></param>
	/// <param name="pGender"></param>
	public Student(string pStudentId, string pFName, string pLName, string pGender){

	}

	public int StudentID{
		get{
			return StudentID;
		}
		set{
			StudentID = value;
		}
	}

	/// <summary>
	/// implements the work function
	/// 
	/// work function should return 'Study, Drink Coffee, Party, Sleep, Repeat'
	/// </summary>
	public override string Work(){

		return "";
	}

}//end Student