///////////////////////////////////////////////////////////
//  TeachSpecialNeeds.cs
//  Implementation of the Class TeachSpecialNeeds
//  Generated by Enterprise Architect
//  Created on:      11-May-2018 8:24:45 PM
//  Original author: STUDENT
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class TeachSpecialNeeds : ITeach {

	public SpecialNeedsTeacher m_SpecialNeedsTeacher;

	public TeachSpecialNeeds(){

	}

	~TeachSpecialNeeds(){

	}

	/// <summary>
	/// Implements the ITeach Interface
	/// 
	/// returns "Teach Special Needs"
	/// </summary>
	public string Teach(){

		return "";
	}

}//end TeachSpecialNeeds