///////////////////////////////////////////////////////////
//  TeachHighSchool.cs
//  Implementation of the Class TeachHighSchool
//  Generated by Enterprise Architect
//  Created on:      11-May-2018 8:24:45 PM
//  Original author: STUDENT
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class TeachHighSchool : ITeach {

	public SecondaryTeacher m_SecondaryTeacher;

	public TeachHighSchool(){

	}

	~TeachHighSchool(){

	}

	/// <summary>
	/// Implements the ITeach Interface
	/// 
	/// returns "Teach High School Brats"
	/// </summary>
	public string Teach(){

		return "";
	}

}//end TeachHighSchool