///////////////////////////////////////////////////////////
//  TeachPAVE.cs
//  Implementation of the Class TeachPAVE
//  Generated by Enterprise Architect
//  Created on:      11-May-2018 8:24:45 PM
//  Original author: STUDENT
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class TeachPAVE : ITeach {

	public PAVETeacher m_PAVETeacher;

	public TeachPAVE(){

	}

	~TeachPAVE(){

	}

	/// <summary>
	/// Implements the ITeach Interface
	/// 
	/// returns "Teach Awesome SWD Students"
	/// </summary>
	public string Teach(){

		return "";
	}

}//end TeachPAVE